[Greeter]
# Fondo y tema
background=/usr/share/pixmaps/login_bg.jpg
theme-name=TokyoNight
icon-theme-name=Papirus-Dark
font-name=JetBrainsMono Nerd Font 11

# Ocultar elementos innecesarios para más minimalismo
draw-user-backgrounds=false
draw-grid=false
show-hostname=false

# Formato del reloj (Hora en el centro arriba)
show-clock=true
clock-format=%I:%M %p
