[colors]
background = #991a1b26
background-alt = #24283b
foreground = #c0caf5
primary = #7aa2f7
secondary = #2ac3de
alert = #f7768e
disabled = #565f89

[bar/mi_barra]
monitor = ${env:MONITOR:}
width = 100%
height = 24pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Nerd Font:size=11;2"
font-1 = "Font Awesome 6 Free Solid:size=11;2"

modules-left = xworkspaces xwindow
modules-center = date
modules-right = xkeyboard filesystem pulseaudio memory cpu disk-root disk-data powermenu 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}
click-right = env GTK_THEME=Tokyonight-Dark pavucontrol

[module/memory]
type = internal/memory
interval = 2
format-prefix = %{A1:ghostty -e btop:}RAM %{A}
format-prefix-foreground = ${colors.primary}
label = %{A1:ghostty -e btop:}%percentage_used:2%%%{A}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = %{A1:ghostty -e btop:}CPU %{A}
format-prefix-foreground = ${colors.primary}
label = %{A1:ghostty -e btop:}%percentage:2%%%{A}

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

[module/powermenu]
type = custom/text
content = " "
content-foreground = ${colors.alert}
click-left = ~/.config/rofi/powermenu.sh

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = scroll lock

; Solo mostrar cuando están activados
format = <label-indicator>

; Diseño para Mayúsculas (Rojo TokyoNight)
label-indicator-on-capslock = "󰪛 MAYÚS "
label-indicator-on-capslock-foreground = #f7768e

; Diseño para Num Lock (Azul TokyoNight)
label-indicator-on-numlock = "󰎦 NUM "
label-indicator-on-numlock-foreground = #7aa2f7

[module/disk-root]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{A1:gparted:}󱛟 %percentage_used%%%{A}
label-mounted-foreground = #bb9af7
click-left = sudo baobab

[module/disk-data]
type = internal/fs
interval = 25
mount-0 = /mnt/datos
label-mounted = %{A1:gparted:}󰋊 %percentage_used%%%{A}
label-mounted-foreground = #7aa2f7

[settings]
screenchange-reload = true
pseudo-transparency = true

